# Generated by Django 5.0.14 on 2026-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ONE_TIME', 'One Time'), ('QUARTERLY', 'Quarterly'), ('INSTALLMENT', 'Installment')], default='MONTHLY', max_length=20),
        ),
    ]
